//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stavadlo22.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Trans {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Trans() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stavadlo22.Resources.Trans", typeof(Trans).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string adresa {
            get {
                return ResourceManager.GetString("adresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP adresa.
        /// </summary>
        public static string adresaIP {
            get {
                return ResourceManager.GetString("adresaIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikácia je pripojená na server!.
        /// </summary>
        public static string appConnectedToServer {
            get {
                return ResourceManager.GetString("appConnectedToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stavadlo 22.
        /// </summary>
        public static string appTitle {
            get {
                return ResourceManager.GetString("appTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brána.
        /// </summary>
        public static string brana {
            get {
                return ResourceManager.GetString("brana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čakajte....
        /// </summary>
        public static string cakajte {
            get {
                return ResourceManager.GetString("cakajte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chybové hlásenia.
        /// </summary>
        public static string chyboveHlasenia {
            get {
                return ResourceManager.GetString("chyboveHlasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyby.
        /// </summary>
        public static string chyby {
            get {
                return ResourceManager.GetString("chyby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo telegramu pre klienta.
        /// </summary>
        public static string cisloTelPreKlienta {
            get {
                return ResourceManager.GetString("cisloTelPreKlienta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo telegramu pre server.
        /// </summary>
        public static string cisloTelPreServer {
            get {
                return ResourceManager.GetString("cisloTelPreServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dráha hasiaceho vozu.
        /// </summary>
        public static string drahaHasiacehoVozu {
            get {
                return ResourceManager.GetString("drahaHasiacehoVozu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dátum a čas do:.
        /// </summary>
        public static string dtDo {
            get {
                return ResourceManager.GetString("dtDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dátum a čas od:.
        /// </summary>
        public static string dtOd {
            get {
                return ResourceManager.GetString("dtOd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter pre výber záznamov.
        /// </summary>
        public static string filterPreVyberZaznamov {
            get {
                return ResourceManager.GetString("filterPreVyberZaznamov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo:.
        /// </summary>
        public static string heslo {
            get {
                return ResourceManager.GetString("heslo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !! Heslo NEBOLO ZMENENÉ, skúste ešte raz !!.
        /// </summary>
        public static string hesloNeboloZmenene {
            get {
                return ResourceManager.GetString("hesloNeboloZmenene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo NEBOLO ZMENENÉ !!.
        /// </summary>
        public static string hesloNeboloZmenene2 {
            get {
                return ResourceManager.GetString("hesloNeboloZmenene2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo bolo úspešne zmenené!.
        /// </summary>
        public static string hesloZmenene {
            get {
                return ResourceManager.GetString("hesloZmenene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Informácie o zariadení.
        /// </summary>
        public static string infoOzariadeni {
            get {
                return ResourceManager.GetString("infoOzariadeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info panel.
        /// </summary>
        public static string infoPanel {
            get {
                return ResourceManager.GetString("infoPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informácie.
        /// </summary>
        public static string informacie {
            get {
                return ResourceManager.GetString("informacie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - izolovaný styk.
        /// </summary>
        public static string izolovanyStyk {
            get {
                return ResourceManager.GetString("izolovanyStyk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - izolovaný úsek.
        /// </summary>
        public static string izolovanyUsek {
            get {
                return ResourceManager.GetString("izolovanyUsek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - izol. styk v prech. priereze.
        /// </summary>
        public static string izolStykVPrechPriereze {
            get {
                return ResourceManager.GetString("izolStykVPrechPriereze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte jeden zo {0} variantov posunovej cesty {1}!.
        /// </summary>
        public static string jedenZoVariantovPosunCesta {
            get {
                return ResourceManager.GetString("jedenZoVariantovPosunCesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte jeden zo {0} variantov posunovej cesty {1} pre výluku, alebo jej zrušenie!.
        /// </summary>
        public static string jedenZoVariantovPosunVylukaZrusenie {
            get {
                return ResourceManager.GetString("jedenZoVariantovPosunVylukaZrusenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte jeden zo {0} variantov vlakovej cesty {1}!.
        /// </summary>
        public static string jedenZoVariantovVlakCesty {
            get {
                return ResourceManager.GetString("jedenZoVariantovVlakCesty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte jeden z {0} variantov vlakovej cesty {1} pre výluku, alebo jej zrušenie!.
        /// </summary>
        public static string jedenZoVariantovVylukaZrusenie {
            get {
                return ResourceManager.GetString("jedenZoVariantovVylukaZrusenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte jeden z {0} variantov posunovej cesty {1}!.
        /// </summary>
        public static string jedenZvariantovPosunCesta {
            get {
                return ResourceManager.GetString("jedenZvariantovPosunCesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte jeden z {0} variantov posunovej cesty {1} pre výluku, alebo jej zrušenie!.
        /// </summary>
        public static string jedenZvariantovPosunVylukaZrusenie {
            get {
                return ResourceManager.GetString("jedenZvariantovPosunVylukaZrusenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte jeden z {0} variantov vlakovej cesty {1}!.
        /// </summary>
        public static string jedenZvariantovVlakCesty {
            get {
                return ResourceManager.GetString("jedenZvariantovVlakCesty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte jeden z {0} variantov vlakovej cesty {1} pre výluku, alebo jej zrušenie!.
        /// </summary>
        public static string jedenZvariantovVylukaZrusenie {
            get {
                return ResourceManager.GetString("jedenZvariantovVylukaZrusenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klient.
        /// </summary>
        public static string klient {
            get {
                return ResourceManager.GetString("klient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komunikačné parametre.
        /// </summary>
        public static string komunikacneParametre {
            get {
                return ResourceManager.GetString("komunikacneParametre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koniec.
        /// </summary>
        public static string koniec {
            get {
                return ResourceManager.GetString("koniec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kritická porucha.
        /// </summary>
        public static string kritickaPorucha {
            get {
                return ResourceManager.GetString("kritickaPorucha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre prihlásenie do programu zadajte meno a heslo.
        /// </summary>
        public static string loginMessage01 {
            get {
                return ResourceManager.GetString("loginMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre opätovné prihlásenie zadajte meno a heslo.
        /// </summary>
        public static string loginMessage02 {
            get {
                return ResourceManager.GetString("loginMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meno:.
        /// </summary>
        public static string meno {
            get {
                return ResourceManager.GetString("meno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meno.
        /// </summary>
        public static string menoKlienta {
            get {
                return ResourceManager.GetString("menoKlienta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koniec.
        /// </summary>
        public static string menu_koniec {
            get {
                return ResourceManager.GetString("menu_koniec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to miestne ovládanie.
        /// </summary>
        public static string miestneOvladanie {
            get {
                return ResourceManager.GetString("miestneOvladanie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nadprúd.
        /// </summary>
        public static string nadprud {
            get {
                return ResourceManager.GetString("nadprud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - nadprúd, porucha prestavenia.
        /// </summary>
        public static string nadprudPoruchaPrest {
            get {
                return ResourceManager.GetString("nadprudPoruchaPrest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nápoveda.
        /// </summary>
        public static string napoveda {
            get {
                return ResourceManager.GetString("napoveda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavenie.
        /// </summary>
        public static string nastavenie {
            get {
                return ResourceManager.GetString("nastavenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Návestidla.
        /// </summary>
        public static string navestidla {
            get {
                return ResourceManager.GetString("navestidla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemáte oprávnenia pre ovládanie daného prvku..
        /// </summary>
        public static string nedostatocneOpravneniaPreZmenuElementa {
            get {
                return ResourceManager.GetString("nedostatocneOpravneniaPreZmenuElementa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - neizolovaný úsek.
        /// </summary>
        public static string neizolovanyUsek {
            get {
                return ResourceManager.GetString("neizolovanyUsek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové heslo:.
        /// </summary>
        public static string noveHeslo {
            get {
                return ResourceManager.GetString("noveHeslo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsadenosti.
        /// </summary>
        public static string obsadenosti {
            get {
                return ResourceManager.GetString("obsadenosti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - obsadený úsek.
        /// </summary>
        public static string obsadenyUsek {
            get {
                return ResourceManager.GetString("obsadenyUsek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhlásenie.
        /// </summary>
        public static string odhlasenie {
            get {
                return ResourceManager.GetString("odhlasenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o pomocných signáloch.
        /// </summary>
        public static string oPomSignaloch {
            get {
                return ResourceManager.GetString("oPomSignaloch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O programe.
        /// </summary>
        public static string oPrograme {
            get {
                return ResourceManager.GetString("oPrograme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o prvku.
        /// </summary>
        public static string oPrvku {
            get {
                return ResourceManager.GetString("oPrvku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o súhlasoch.
        /// </summary>
        public static string oSuhlasoch {
            get {
                return ResourceManager.GetString("oSuhlasoch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o symboloch.
        /// </summary>
        public static string oSymboloch {
            get {
                return ResourceManager.GetString("oSymboloch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to otvoriť.
        /// </summary>
        public static string otvorit {
            get {
                return ResourceManager.GetString("otvorit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o zariadení.
        /// </summary>
        public static string oZariadeni {
            get {
                return ResourceManager.GetString("oZariadeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označenie obsadenia.
        /// </summary>
        public static string oznacenieObsadenia {
            get {
                return ResourceManager.GetString("oznacenieObsadenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte návestidlo pre privolávaciu návesť!.
        /// </summary>
        public static string oznacNavestPrivolNavest {
            get {
                return ResourceManager.GetString("oznacNavestPrivolNavest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte cestu na zrušenie!.
        /// </summary>
        public static string oznacteCestuNaZrusenie {
            get {
                return ResourceManager.GetString("oznacteCestuNaZrusenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte jednu z {0} ciest na zrušenie!.
        /// </summary>
        public static string oznacteJednuZ {
            get {
                return ResourceManager.GetString("oznacteJednuZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte jednu zo {0} ciest na zrušenie!.
        /// </summary>
        public static string oznacteJednuZo {
            get {
                return ResourceManager.GetString("oznacteJednuZo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte koniec posunovej cesty!.
        /// </summary>
        public static string oznacteKoniecPosunCesty {
            get {
                return ResourceManager.GetString("oznacteKoniecPosunCesty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte koniec posunovej cesty pre výluku, alebo jej zrušenie!.
        /// </summary>
        public static string oznacteKoniecPosunCestyVyluka {
            get {
                return ResourceManager.GetString("oznacteKoniecPosunCestyVyluka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte koniec vlakovej cesty pre výluku, alebo jej zrušenie!.
        /// </summary>
        public static string oznacteKoniecVlakCestaVyluka {
            get {
                return ResourceManager.GetString("oznacteKoniecVlakCestaVyluka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte koniec vlakovej cesty!.
        /// </summary>
        public static string oznacteKoniecVlakCesty {
            get {
                return ResourceManager.GetString("oznacteKoniecVlakCesty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte návestidlo určené na výluku, alebo k jej zrušeniu!.
        /// </summary>
        public static string oznacteNavestidloVyluka {
            get {
                return ResourceManager.GetString("oznacteNavestidloVyluka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte návestidlo určené na simuláciu poruchy červenej!.
        /// </summary>
        public static string oznacteNavSimPorCervenej {
            get {
                return ResourceManager.GetString("oznacteNavSimPorCervenej", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte návestidlo určené na simuláciu poruchy povoľovacej návesti!.
        /// </summary>
        public static string oznacteNavSimPovolNav {
            get {
                return ResourceManager.GetString("oznacteNavSimPovolNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte prvok pre zobrazenie informácií o zariadení!.
        /// </summary>
        public static string oznactePrvokInfoZar {
            get {
                return ResourceManager.GetString("oznactePrvokInfoZar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte prvok na zrušenie poruchy!.
        /// </summary>
        public static string oznactePrvokPreZrusPoruchy {
            get {
                return ResourceManager.GetString("oznactePrvokPreZrusPoruchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte prvok pre zobrazenie jeho informácií!.
        /// </summary>
        public static string oznactePrvokZobrInfo {
            get {
                return ResourceManager.GetString("oznactePrvokZobrInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte  koľaj pre vyslanie žiadosti o súhlas.
        /// </summary>
        public static string oznacteUsekOdchod {
            get {
                return ResourceManager.GetString("oznacteUsekOdchod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte úsek pre označenie obsadenia, alebo pre jeho zrušenie!.
        /// </summary>
        public static string oznacteUsekOznacObsad {
            get {
                return ResourceManager.GetString("oznacteUsekOznacObsad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte úsek pre vyslanie žiadosti o súhlas pre odchod posunovou cestou!.
        /// </summary>
        public static string oznacteUsekPosunCestaOdchod {
            get {
                return ResourceManager.GetString("oznacteUsekPosunCestaOdchod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte úsek pre nastavenie, alebo zrušenie simulácie obsadenia!.
        /// </summary>
        public static string oznacteUsekSimObsadenia {
            get {
                return ResourceManager.GetString("oznacteUsekSimObsadenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte úsek pre udelenie súhlasu!.
        /// </summary>
        public static string oznacteUsekUdelSuhlas {
            get {
                return ResourceManager.GetString("oznacteUsekUdelSuhlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte koľaj pre udelenie súhlasu!.
        /// </summary>
        public static string oznacteUsekUdelSuhlasu {
            get {
                return ResourceManager.GetString("oznacteUsekUdelSuhlasu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte úsek určený k uvoľneniu izolácie!.
        /// </summary>
        public static string oznacteUsekUvolIzol {
            get {
                return ResourceManager.GetString("oznacteUsekUvolIzol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte úsek pre vyslanie žiadosti o súhlas pre odchod vlakovou cestou!.
        /// </summary>
        public static string oznacteUsekVlakCestaOdchod {
            get {
                return ResourceManager.GetString("oznacteUsekVlakCestaOdchod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte úsek pre zrušenie súhlasu!.
        /// </summary>
        public static string oznacteUsekZrusSuhlas {
            get {
                return ResourceManager.GetString("oznacteUsekZrusSuhlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte koľaj pre zrušenie súhlasu!.
        /// </summary>
        public static string oznacteUsekZrusSuhlasu {
            get {
                return ResourceManager.GetString("oznacteUsekZrusSuhlasu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte výmenu určenú na simuláciu poruchy nadprúdu!.
        /// </summary>
        public static string oznacteVymenuPoruchaNadprud {
            get {
                return ResourceManager.GetString("oznacteVymenuPoruchaNadprud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte výmenu určenú na simuláciu poruchy prestavenia!.
        /// </summary>
        public static string oznacteVymenuPoruchaPrest {
            get {
                return ResourceManager.GetString("oznacteVymenuPoruchaPrest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte výmenu určenú na simuláciu poruchy rozrezu!.
        /// </summary>
        public static string oznacteVymenuPoruchaRozrez {
            get {
                return ResourceManager.GetString("oznacteVymenuPoruchaRozrez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte výmenu určenú na prestavenie!.
        /// </summary>
        public static string oznacteVymenuPrestavenie {
            get {
                return ResourceManager.GetString("oznacteVymenuPrestavenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte výmenu určenú na simuláciu poruchy straty dohliadania!.
        /// </summary>
        public static string oznacteVymenuStrataDohl {
            get {
                return ResourceManager.GetString("oznacteVymenuStrataDohl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte výmenu na vykonanie západkovej skúšky!.
        /// </summary>
        public static string oznacteVymenuZapadSkuska {
            get {
                return ResourceManager.GetString("oznacteVymenuZapadSkuska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte výmenu určenú na úplnú výluku, alebo jej zrušenie!.
        /// </summary>
        public static string oznacteVymUplnaVyluka {
            get {
                return ResourceManager.GetString("oznacteVymUplnaVyluka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte výmenu určenú na výluku prestavenia, alebo jej zrušenie!.
        /// </summary>
        public static string oznacteVymVylukaPrestav {
            get {
                return ResourceManager.GetString("oznacteVymVylukaPrestav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte začiatok posunovej cesty!.
        /// </summary>
        public static string oznacteZacPosunCesty {
            get {
                return ResourceManager.GetString("oznacteZacPosunCesty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte začiatok posunovej cesty určenej pre výluku, alebo jej zrušenie!.
        /// </summary>
        public static string oznacteZacPosunCestyVyluka {
            get {
                return ResourceManager.GetString("oznacteZacPosunCestyVyluka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte začiatok vlakovej cesty určenej pre výluku, alebo  jej zrušenie!.
        /// </summary>
        public static string oznacteZacVlakCestaVyluka {
            get {
                return ResourceManager.GetString("oznacteZacVlakCestaVyluka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte začiatok vlakovej cesty!.
        /// </summary>
        public static string oznacteZacVlakCesty {
            get {
                return ResourceManager.GetString("oznacteZacVlakCesty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to panely.
        /// </summary>
        public static string panely {
            get {
                return ResourceManager.GetString("panely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pcesta.
        /// </summary>
        public static string Pcesta {
            get {
                return ResourceManager.GetString("Pcesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFunkcie.
        /// </summary>
        public static string PFunkcie {
            get {
                return ResourceManager.GetString("PFunkcie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemáte žiadne ovládanie, požiadajte druhého operátora o privilégia..
        /// </summary>
        public static string pokusOOdovzanieOvladaniaBezPrav {
            get {
                return ResourceManager.GetString("pokusOOdovzanieOvladaniaBezPrav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informácie.
        /// </summary>
        public static string pomInfo {
            get {
                return ResourceManager.GetString("pomInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pomocné.
        /// </summary>
        public static string pomocne {
            get {
                return ResourceManager.GetString("pomocne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pomocné symboly.
        /// </summary>
        public static string pomSymboly {
            get {
                return ResourceManager.GetString("pomSymboly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to návestidla.
        /// </summary>
        public static string porucha_navestidla {
            get {
                return ResourceManager.GetString("porucha_navestidla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porucha červenej.
        /// </summary>
        public static string poruchaCervenej {
            get {
                return ResourceManager.GetString("poruchaCervenej", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - porucha návestidla.
        /// </summary>
        public static string poruchaNavestidla {
            get {
                return ResourceManager.GetString("poruchaNavestidla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porucha povoľovacej návesti.
        /// </summary>
        public static string poruchaPovolovacejNavesti {
            get {
                return ResourceManager.GetString("poruchaPovolovacejNavesti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porucha prestavenia.
        /// </summary>
        public static string poruchaPrestavenia {
            get {
                return ResourceManager.GetString("poruchaPrestavenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poruchy.
        /// </summary>
        public static string poruchy {
            get {
                return ResourceManager.GetString("poruchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Posun dovolený.
        /// </summary>
        public static string posunDovoleny {
            get {
                return ResourceManager.GetString("posunDovoleny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Posun nedovolený.
        /// </summary>
        public static string posunNedovoleny {
            get {
                return ResourceManager.GetString("posunNedovoleny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Posun nezabezpečený dovolený.
        /// </summary>
        public static string posunNezabDovoleny {
            get {
                return ResourceManager.GetString("posunNezabDovoleny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - posunová cesta.
        /// </summary>
        public static string posunovaCesta {
            get {
                return ResourceManager.GetString("posunovaCesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to posunovej cesty.
        /// </summary>
        public static string posunovejCesty {
            get {
                return ResourceManager.GetString("posunovejCesty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Posun zabezpečený dovolený.
        /// </summary>
        public static string posunZabDovoleny {
            get {
                return ResourceManager.GetString("posunZabDovoleny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to povoliť.
        /// </summary>
        public static string povolit {
            get {
                return ResourceManager.GetString("povolit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pozadie.
        /// </summary>
        public static string pozadie {
            get {
                return ResourceManager.GetString("pozadie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozadie.
        /// </summary>
        public static string pozadieStavadloPage {
            get {
                return ResourceManager.GetString("pozadieStavadloPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pre obsluhu V801.
        /// </summary>
        public static string preObsluhuV801 {
            get {
                return ResourceManager.GetString("preObsluhuV801", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pre posunovú cestu.
        /// </summary>
        public static string prePusunovuCestu {
            get {
                return ResourceManager.GetString("prePusunovuCestu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prestavenia.
        /// </summary>
        public static string prestavenia {
            get {
                return ResourceManager.GetString("prestavenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prestavenie vymeny - začiatok 10s intervalu.
        /// </summary>
        public static string prestavenieVymeny10sZaciatok {
            get {
                return ResourceManager.GetString("prestavenieVymeny10sZaciatok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pre vlakovú cestu.
        /// </summary>
        public static string preVlakovuCestu {
            get {
                return ResourceManager.GetString("preVlakovuCestu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prihlásenie.
        /// </summary>
        public static string prihlasenie {
            get {
                return ResourceManager.GetString("prihlasenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prihlásenie a odhlásenie.
        /// </summary>
        public static string prihlasenieAOdhlasenie {
            get {
                return ResourceManager.GetString("prihlasenieAOdhlasenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to len prihlásenia/odhlásenia.
        /// </summary>
        public static string prihlasenieOdhlasenie {
            get {
                return ResourceManager.GetString("prihlasenieOdhlasenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prihlásenie užívateľa.
        /// </summary>
        public static string prihlasenieUzivatela {
            get {
                return ResourceManager.GetString("prihlasenieUzivatela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privolávacia návesť.
        /// </summary>
        public static string privolavaciaNavest {
            get {
                return ResourceManager.GetString("privolavaciaNavest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program bude ukončený!.
        /// </summary>
        public static string programBudeUkonceny {
            get {
                return ResourceManager.GetString("programBudeUkonceny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastaví počiatočné podmienky pre filter.
        /// </summary>
        public static string resetFilter {
            get {
                return ResourceManager.GetString("resetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to riadenie.
        /// </summary>
        public static string riadenie {
            get {
                return ResourceManager.GetString("riadenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rola:.
        /// </summary>
        public static string rola {
            get {
                return ResourceManager.GetString("rola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleManager:.
        /// </summary>
        public static string roleManager {
            get {
                return ResourceManager.GetString("roleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleManager nie je prístupný!.
        /// </summary>
        public static string roleManagerIsDisabled {
            get {
                return ResourceManager.GetString("roleManagerIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozrez.
        /// </summary>
        public static string rozrez {
            get {
                return ResourceManager.GetString("rozrez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - rozrez.
        /// </summary>
        public static string rozrezInfo {
            get {
                return ResourceManager.GetString("rozrezInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rozvádzače.
        /// </summary>
        public static string rozvadzace {
            get {
                return ResourceManager.GetString("rozvadzace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rušenie.
        /// </summary>
        public static string rusenia {
            get {
                return ResourceManager.GetString("rusenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string server {
            get {
                return ResourceManager.GetString("server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signálu.
        /// </summary>
        public static string signalu {
            get {
                return ResourceManager.GetString("signalu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulácia.
        /// </summary>
        public static string simulacia {
            get {
                return ResourceManager.GetString("simulacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte koľaj pre vyslanie žiadosti o súhlas.
        /// </summary>
        public static string simulZiadostSuhlas {
            get {
                return ResourceManager.GetString("simulZiadostSuhlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sklad žiaruvzdorného materiálu.
        /// </summary>
        public static string skladZVM {
            get {
                return ResourceManager.GetString("skladZVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sklad žiaruvzdorného.
        /// </summary>
        public static string skladZVM1 {
            get {
                return ResourceManager.GetString("skladZVM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to materialu.
        /// </summary>
        public static string skladZVM2 {
            get {
                return ResourceManager.GetString("skladZVM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa pre server:.
        /// </summary>
        public static string spravaPreServer {
            get {
                return ResourceManager.GetString("spravaPreServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa zo servera:.
        /// </summary>
        public static string spravaZoServera {
            get {
                return ResourceManager.GetString("spravaZoServera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to len spustenia/skončenia.
        /// </summary>
        public static string spustenieUkoncenie {
            get {
                return ResourceManager.GetString("spustenieUkoncenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spustí prehrávanie vybratých záznamov.
        /// </summary>
        public static string spustiPrehravanieZaznamov {
            get {
                return ResourceManager.GetString("spustiPrehravanieZaznamov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spustiť prehrávanie.
        /// </summary>
        public static string spustitPrehravanie {
            get {
                return ResourceManager.GetString("spustitPrehravanie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staré heslo:.
        /// </summary>
        public static string stareHeslo {
            get {
                return ResourceManager.GetString("stareHeslo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stavadlo.
        /// </summary>
        public static string stavadlo {
            get {
                return ResourceManager.GetString("stavadlo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Stoj.
        /// </summary>
        public static string stoj {
            get {
                return ResourceManager.GetString("stoj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strata dohliadania.
        /// </summary>
        public static string strataDohliadania {
            get {
                return ResourceManager.GetString("strataDohliadania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - strata dohliadania.
        /// </summary>
        public static string strataDohliadaniaInfo {
            get {
                return ResourceManager.GetString("strataDohliadaniaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stredná poloha radičov.
        /// </summary>
        public static string strednaPolohaRadicov {
            get {
                return ResourceManager.GetString("strednaPolohaRadicov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to len chybové hlásenia.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Súbor sa nepodarilo nájsť!.
        /// </summary>
        public static string suborNenajdeny {
            get {
                return ResourceManager.GetString("suborNenajdeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Súhlas.
        /// </summary>
        public static string suhlas {
            get {
                return ResourceManager.GetString("suhlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - súhlas pre odchod.
        /// </summary>
        public static string suhlasOdchod {
            get {
                return ResourceManager.GetString("suhlasOdchod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Súhlasu.
        /// </summary>
        public static string suhlasu {
            get {
                return ResourceManager.GetString("suhlasu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - súhlas pre vchod.
        /// </summary>
        public static string suhlasVchod {
            get {
                return ResourceManager.GetString("suhlasVchod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - súhlas pre vstup.
        /// </summary>
        public static string suhlasVstup {
            get {
                return ResourceManager.GetString("suhlasVstup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sys. Chyby.
        /// </summary>
        public static string sysChyby {
            get {
                return ResourceManager.GetString("sysChyby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stavanie posunových ciest.
        /// </summary>
        public static string tooltipPcesta {
            get {
                return ResourceManager.GetString("tooltipPcesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prihlásenie, nastavenia, informácie.
        /// </summary>
        public static string tooltipPFunkcie {
            get {
                return ResourceManager.GetString("tooltipPFunkcie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Núdzový stop.
        /// </summary>
        public static string tooltipStop {
            get {
                return ResourceManager.GetString("tooltipStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsluha súhlasov.
        /// </summary>
        public static string tooltipSuhlas {
            get {
                return ResourceManager.GetString("tooltipSuhlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rušenie porúch, výluky, uvoľnenie izolacie.
        /// </summary>
        public static string tooltipUdrzba {
            get {
                return ResourceManager.GetString("tooltipUdrzba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stavanie vlakových ciest.
        /// </summary>
        public static string tooltipVcesta {
            get {
                return ResourceManager.GetString("tooltipVcesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individuálne prestavenie výmen.
        /// </summary>
        public static string tooltipVymeny {
            get {
                return ResourceManager.GetString("tooltipVymeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rušenie jazdných ciest.
        /// </summary>
        public static string tooltipZrus {
            get {
                return ResourceManager.GetString("tooltipZrus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udelenie.
        /// </summary>
        public static string udelenia {
            get {
                return ResourceManager.GetString("udelenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udelenie súhlasu.
        /// </summary>
        public static string udelenieSuhlasu {
            get {
                return ResourceManager.GetString("udelenieSuhlasu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Údržba.
        /// </summary>
        public static string udrzba {
            get {
                return ResourceManager.GetString("udrzba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre ukončenie privolávacej návesti uvoľnite tlačidlo!.
        /// </summary>
        public static string ukonceniePrivolNavesti {
            get {
                return ResourceManager.GetString("ukonceniePrivolNavesti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to úplná.
        /// </summary>
        public static string uplna {
            get {
                return ResourceManager.GetString("uplna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - úplná výluka.
        /// </summary>
        public static string uplnaVyluka {
            get {
                return ResourceManager.GetString("uplnaVyluka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - uvoľnená izolácia.
        /// </summary>
        public static string uvolnenaIzolacia {
            get {
                return ResourceManager.GetString("uvolnenaIzolacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uvoľnenie izolácie.
        /// </summary>
        public static string uvolnenieIzolacie {
            get {
                return ResourceManager.GetString("uvolnenieIzolacie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Užívatelia.
        /// </summary>
        public static string uzivatela {
            get {
                return ResourceManager.GetString("uzivatela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vápenca.
        /// </summary>
        public static string vapenca {
            get {
                return ResourceManager.GetString("vapenca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vcesta.
        /// </summary>
        public static string Vcesta {
            get {
                return ResourceManager.GetString("Vcesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veľká Ida.
        /// </summary>
        public static string VelkaIda {
            get {
                return ResourceManager.GetString("VelkaIda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifikácia:.
        /// </summary>
        public static string veriftikacia {
            get {
                return ResourceManager.GetString("veriftikacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzia.
        /// </summary>
        public static string verzia {
            get {
                return ResourceManager.GetString("verzia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLR verzia.
        /// </summary>
        public static string verziaCLR {
            get {
                return ResourceManager.GetString("verziaCLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - vlaková cesta.
        /// </summary>
        public static string vlakovaCesta {
            get {
                return ResourceManager.GetString("vlakovaCesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vlakovej cesty.
        /// </summary>
        public static string vlakovejCesty {
            get {
                return ResourceManager.GetString("vlakovejCesty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Voľno.
        /// </summary>
        public static string volno {
            get {
                return ResourceManager.GetString("volno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to všetko.
        /// </summary>
        public static string vsetko {
            get {
                return ResourceManager.GetString("vsetko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybavenie porúch.
        /// </summary>
        public static string vybaveniePoruch {
            get {
                return ResourceManager.GetString("vybaveniePoruch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výber logovacích záznamov z databázy.
        /// </summary>
        public static string vyberLogSuborovZDB {
            get {
                return ResourceManager.GetString("vyberLogSuborovZDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybraté log súbory.
        /// </summary>
        public static string vybrateLogSubory {
            get {
                return ResourceManager.GetString("vybrateLogSubory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybraté záznamy.
        /// </summary>
        public static string vybrateZaznamy {
            get {
                return ResourceManager.GetString("vybrateZaznamy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybrať údaje.
        /// </summary>
        public static string vybratUdaje {
            get {
                return ResourceManager.GetString("vybratUdaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - výhybka v manipulácii.
        /// </summary>
        public static string vyhybkaVManipulacii {
            get {
                return ResourceManager.GetString("vyhybkaVManipulacii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - výhybka v polohe +/-.
        /// </summary>
        public static string vyhybkaVPolohe {
            get {
                return ResourceManager.GetString("vyhybkaVPolohe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výluka.
        /// </summary>
        public static string vyluka {
            get {
                return ResourceManager.GetString("vyluka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - výluka návestidla.
        /// </summary>
        public static string vylukaNavestidla {
            get {
                return ResourceManager.GetString("vylukaNavestidla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - výluka prestavenia.
        /// </summary>
        public static string vylukaPrestaveniaBrush {
            get {
                return ResourceManager.GetString("vylukaPrestaveniaBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výmeny.
        /// </summary>
        public static string vymeny {
            get {
                return ResourceManager.GetString("vymeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výpis filtrovaných údajov.
        /// </summary>
        public static string vypisFiltrovanychUdajov {
            get {
                return ResourceManager.GetString("vypisFiltrovanychUdajov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyslanie žiadosti o súhlas pre obsluhu V801!.
        /// </summary>
        public static string vyslanieZiadostiV801Suhlas {
            get {
                return ResourceManager.GetString("vyslanieZiadostiV801Suhlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výsypná jama.
        /// </summary>
        public static string vysypnaJama {
            get {
                return ResourceManager.GetString("vysypnaJama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte začiatok ďalšej posunovej cesty!.
        /// </summary>
        public static string zaciatokDalsejPosunCesty {
            get {
                return ResourceManager.GetString("zaciatokDalsejPosunCesty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte začiatok ďalšej posunovej cesty pre výluku, alebo jej zrušenie!.
        /// </summary>
        public static string zaciatokDalsejPosunCestyVyluka {
            get {
                return ResourceManager.GetString("zaciatokDalsejPosunCestyVyluka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Označte začiatok ďalšej vlakovej cesty!.
        /// </summary>
        public static string zaciatokDalsejVlakCesty {
            get {
                return ResourceManager.GetString("zaciatokDalsejVlakCesty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zakázať.
        /// </summary>
        public static string zakazat {
            get {
                return ResourceManager.GetString("zakazat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Západková skúška.
        /// </summary>
        public static string zapadkovaSkuska {
            get {
                return ResourceManager.GetString("zapadkovaSkuska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zavrieť.
        /// </summary>
        public static string zavriet {
            get {
                return ResourceManager.GetString("zavriet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Záznam.
        /// </summary>
        public static string zaznam {
            get {
                return ResourceManager.GetString("zaznam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prehrať záznamy.
        /// </summary>
        public static string zaznamPrehrat {
            get {
                return ResourceManager.GetString("zaznamPrehrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zoradiť.
        /// </summary>
        public static string zaznamZoradit {
            get {
                return ResourceManager.GetString("zaznamZoradit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybrať záznamy pre prehrávanie.
        /// </summary>
        public static string zaznamZvolit {
            get {
                return ResourceManager.GetString("zaznamZvolit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žiadosť.
        /// </summary>
        public static string ziadosti {
            get {
                return ResourceManager.GetString("ziadosti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - žiadosť pre odchod.
        /// </summary>
        public static string ziadostOdchod {
            get {
                return ResourceManager.GetString("ziadostOdchod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žiadosť o súhlas.
        /// </summary>
        public static string ziadostOSuhlas {
            get {
                return ResourceManager.GetString("ziadostOSuhlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - žiadosť pre vchod.
        /// </summary>
        public static string ziadostVchod {
            get {
                return ResourceManager.GetString("ziadostVchod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - žiadosť pre vstup.
        /// </summary>
        public static string ziadostVstup {
            get {
                return ResourceManager.GetString("ziadostVstup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmena hesla.
        /// </summary>
        public static string zmenaHesla {
            get {
                return ResourceManager.GetString("zmenaHesla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zo Servera.
        /// </summary>
        public static string zoServera {
            get {
                return ResourceManager.GetString("zoServera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zruš.
        /// </summary>
        public static string zrus {
            get {
                return ResourceManager.GetString("zrus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušenie poruchy.
        /// </summary>
        public static string zruseniePoruchy {
            get {
                return ResourceManager.GetString("zruseniePoruchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rušenie súhlasu .
        /// </summary>
        public static string zrusenieSuhlasu {
            get {
                return ResourceManager.GetString("zrusenieSuhlasu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žurnál.
        /// </summary>
        public static string zurnal {
            get {
                return ResourceManager.GetString("zurnal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žurnály.
        /// </summary>
        public static string zurnaly {
            get {
                return ResourceManager.GetString("zurnaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zvuk.
        /// </summary>
        public static string zvuk {
            get {
                return ResourceManager.GetString("zvuk", resourceCulture);
            }
        }
    }
}
